waypoints:
  - name: Goal_1
    position:
      x: 0.0
      y: 3.0
      z: 0.0
    orientation:
      w: 1.0
      x: 0.0
      y: 0.0
      z: 0.0
  - name: Goal_2
    position:
      x: 6.0
      y: 4.0
      z: 0.0
    orientation:
      w: 0.9659
      x: 0.0
      y: 0.0
      z: 0.2588
  - name: Goal_3
    position:
      x: 6.5
      y: -1.4
      z: 0.0
    orientation:
      w: 0.0
      x: 0.0
      y: 0.0
      z: 1.0
  - name: Goal_4
    position:
      x: -1.6
      y: -2.5
      z: 0.0
    orientation:
      w: 0.7934
      x: 0.0
      y: 0.0
      z: 0.6088
